stages:
  - test
  - sbom

default:
  tags:
    - flarenetwork
  artifacts:
    expire_in: 3 days

include:
  - component: gitlab.com/flarenetwork/ci-components-private/lgtm@2
  - component: gitlab.com/flarenetwork/ci-components-private/dependency-track@2
  - component: gitlab.com/flarenetwork/ci-components-private/lint-dockerfile@2
  - component: gitlab.com/flarenetwork/ci-components-private/lint-shell@2
  - template: Jobs/Secret-Detection.latest.gitlab-ci.yml
  - component: gitlab.com/flarenetwork/ci-components-private/lint-pnpm@2
    inputs:
      node_version: '24.13'
      lint_commands: |
        pnpm lint:check
        pnpm format:check
  - component: gitlab.com/flarenetwork/ci-components-private/test-pnpm@2
    inputs:
      node_version: '24.13'
      tags: ["flarenetwork-md"]
      coverage_enabled: true
      coverage_regex: '/^Lines\s*:\s*(\d+(?:\.\d+)?)%/'
      test_commands: |
        pnpm test:coverage
